bin: early return while running generators (#947)

diff --git a/bin/run-generators b/bin/run-generators
--- a/bin/run-generators
+++ b/bin/run-generators
@@ -5,7 +5,11 @@ for dir in exercises/*/; do
   if [ -f $file ]; then
     cd "$dir/.meta"
     echo "Generating $(basename $dir)"
-    go run gen.go
+    if ! go run gen.go; then
+      echo "[FAIL]: Generator $(basename $dir) gives error"
+      exit $?
+    fi
     cd -
   fi
 done
+echo "[SUCCESS]: All generators are run"
