adjusted execution of linter/tests

diff --git a/bin/test-without-stubs b/bin/test-without-stubs
--- a/bin/test-without-stubs
+++ b/bin/test-without-stubs
@@ -104,4 +104,16 @@ if [ $exitcode -ne 0 ]
     exit $exitcode
 fi
 
-bin/golangci-lint run ./gen/... ./gomod-sync/... && go test -cpu 2 ./gen/... ./gomod-sync/...
+paths_to_lint="gomod-sync gen"
+for $path in $paths_to_lint; do
+  cd "$root"
+  cd "$path"
+  bin/golangci-lint run && go test -cpu 2
+
+  exitcode=$?
+  if [ $exitcode -ne 0 ]
+    then 
+      echo "LINTER/TESTS FAILED for $path"
+      exit $exitcode
+  fi
+done
