added generator and gomod-sync to CI

diff --git a/bin/test-without-stubs b/bin/test-without-stubs
--- a/bin/test-without-stubs
+++ b/bin/test-without-stubs
@@ -82,7 +82,7 @@ cleanup () {
   rm -rf $tmp
 }
 
-trap cleanup EXIT INT TERM
+#trap cleanup EXIT INT TERM
 
 # Since Go 1.16 all go commands run in module-aware mode,
 # which would require a go.mod file to be present at the root
@@ -91,10 +91,16 @@ trap cleanup EXIT INT TERM
 # module-aware mode only in places where a go.mod is present.
 export GO111MODULE=auto
 
-# This is the last command in the file,
-# so the exit status of this script is the exit status of go test.
-# If this ever changes, remember to preserve the exit status accordingly.
-# Otherwise CI may falsely report a test as passed when it has failed.
 # Run lint which is configured by .golangci.yml at the root of the repo
 # and if it's successful, run tests
 bin/golangci-lint run ./$tmp/... && go test -cpu 2 ./$tmp/...
+
+exitcode=$?
+
+if [ $exitcode -ne 0 ]
+  then 
+    echo "LINTER/TESTS FAILED for exercises or exercise generators"
+    exit $exitcode
+fi
+
+bin/golangci-lint run ./gen/... ./gomod-sync/... && go test -cpu 2 ./gen/... ./gomod-sync/...
