Mild tweaks to CI tests

diff --git a/bin/test-without-stubs b/bin/test-without-stubs
--- a/bin/test-without-stubs
+++ b/bin/test-without-stubs
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # This test suite:
 # (1) moves all go files (and modules) into a tmp directory,
@@ -16,7 +16,8 @@
 # One downside to this is that the errors generated reference the temporary
 # file locations rather than the real ones, but we deemed this cost acceptable.
 
-tmp=tmp/lint
+root=$(pwd)
+tmp="${root}/tmp/lint"
 mkdir -p $tmp
 
 for parentdir in concept practice; do
@@ -25,18 +26,24 @@ for parentdir in concept practice; do
     if [ -f "${dir}.meta/.skip_tests" ]; then
       continue
     fi
-    file="${dir}${stub}.go"
-    exemplar=$(find ${dir}.meta/ex*.go)
+    exemplar="${dir}.meta/exemplar.go"
+    if [ ! -f $exemplar ]; then
+      exemplar="${dir}.meta/example.go"
+    fi
+    if [ ! -f $exemplar ]; then
+      echo "Missing examplar in ${dir}.meta called exemplar.go or example.go"
+      exit 1
+    fi
     mod="${dir}go.mod"
     if [ ! -f $mod ]; then
-      echo "Creating a basic go module at $mod, like this:"
+      echo "Please add a basic go module at $mod, like this:"
       cat << EOD
 module $stub
 
 go 1.14
 EOD
       exit 1
-    elif [ -f $file ] && [ -f $exemplar ]; then
+    elif [ -f "${dir}${stub}.go" ] ; then
       tmpstub=$tmp/$parentdir/$stub
       mkdir -p $tmpstub
       echo "copy base files and tests to $tmpstub"
@@ -46,13 +53,11 @@ EOD
       echo "copy module $mod to $tmpstub"
       cp $mod $tmpstub
       echo "put everything in the same module"
-      sed -i "s/package .*/package ${stub}/" $tmpstub/*.go
-      sed -i "s/module .*/module ${stub}/" $tmpstub/go.mod
+      sed -i'.bak' "s|package .*|package ${stub}|" $tmpstub/*.go
+      sed -i'.bak' "s|module .*|module ${stub}|" $tmpstub/go.mod
     fi
   done
 done
-
-root=$(pwd)
 
 cleanup () {
   echo "deleting ${tmp}"
@@ -68,7 +73,7 @@ trap cleanup EXIT INT TERM
 # This is the last command in the file,
 # so the exit status of this script is the exit status of go test.
 # If this ever changes, remember to preserve the exit status accordingly.
-# Otherwise Travis may falsely report a test as passed when it has failed.
+# Otherwise CI may falsely report a test as passed when it has failed.
 # Run lint which is configured by .golangci.yml at the root of the repo
 # and if it's successful, run tests
-bin/golangci-lint run ./$tmp/... && go test -cpu 2 ./$tmp/...
+bin/golangci-lint run $tmp/... && go test -cpu 2 $tmp/...
